### ISSUE TITLE
Samples not loading map with error: qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

### ISSUE THREAD

**Issue by calicoder77** [Esri/arcgis-maps-sdk-samples-qt#1579]
Good day, I've forked a local copy of the repo and tried to run a bunch of samples. It builds correctly, no errors and I've added my API key as well in main.cpp. The problem is the map doesn't load with the error: `qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed`. Is there a workaround for this?

**Screenshot**
![image](https://user-images.githubusercontent.com/102272619/215143728-39b30462-d595-4a35-b38d-28227125c7aa.png)

**Comment by tanneryould** [comment]
Hi @calicoder77 thanks for reaching out! It look like you may not have SSL in your build environment. You can learn more about that [here](https://developers.arcgis.com/qt/install-and-set-up/#download-the-qt-framework-for-windows-and-qt-creator) on step two of our installation guide for Windows. The Qt Company recommends using [OpenSSL](https://www.openssl.org/) for that. I hope that helps and don't hesitate to follow up!

**Comment by calicoder77** [comment]
> Hi @calicoder77 thanks for reaching out! It look like you may not have SSL in your build environment. You can learn more about that [here](https://developers.arcgis.com/qt/install-and-set-up/#download-the-qt-framework-for-windows-and-qt-creator) on step two of our installation guide for Windows. The Qt Company recommends using [OpenSSL](https://www.openssl.org/) for that. I hope that helps and don't hesitate to follow up!

That was it, I ran QT maintenance tool again and saw that the OpenSSL 1.1.1g option wasn't installed. Installed it now and we're all good.

Thank you!
