### ISSUE TITLE
Is QT Creator the only option? Do samples work in Visual Studio 2019?

### ISSUE THREAD

**Issue by calicoder77** [Esri/arcgis-maps-sdk-samples-qt#1580]
Good day folks, just wondering while I play with the samples in QT Creator. Can we load these in Visual Studio 2019 as it's not working for me. I used the QT VS Tools open .pro option and get all sorts of errors when it completes. Here's a few that pop up:

```
Error (active) E1696 cannot open source file "ArcGISRuntimeEnvironment.h"
Error (active) E1696 cannot open source file "QDir"
Error (active) E1696	cannot open source file "QGuiApplication"
Error (active) E1696	cannot open source file "QQmlApplicationEngine"
Error MSB4094 "SketchOnMap.h;SketchOnMap.h" is an invalid value for the "Item" parameter of the "GetItemHash" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskItem".	
```

I'm familiar with VS since my childhood and is QT Creator the only way to use these samples?

Thanks again for any tips / help.

**Comment by tanneryould** [comment]
Potentially it could work, but our dev team uses Qt Creator and that's what we test on and support, so I wasn't able to get any specific instructions from anyone to help you run the samples in VS. Currently our samples all use QMake and Visual Studio may be better supported if and when we use CMake in the samples, but that's some time down the road.

Sorry I can't be of more help, but perhaps there's something in these resources that can help you

* https://doc.qt.io/qtvstools/qtvstools-getting-started.html
* https://stackoverflow.com/questions/59541102/why-can-visual-studio-2019-not-find-the-qt-include-files
* https://www.qtcentre.org/threads/39525-Configuring-Visual-Studio-for-QT-quot-Error-Cannot-open-source-file-QApplication-quot

**Comment by calicoder77** [comment]
> Potentially it could work, but our dev team uses Qt Creator and that's what we test on and support, so I wasn't able to get any specific instructions from anyone to help you run the samples in VS. Currently our samples all use QMake and Visual Studio may be better supported if and when we use CMake in the samples, but that's some time down the road.
> 
> Sorry I can't be of more help, but perhaps there's something in these resources that can help you
> 
> * https://doc.qt.io/qtvstools/qtvstools-getting-started.html
> * https://stackoverflow.com/questions/59541102/why-can-visual-studio-2019-not-find-the-qt-include-files
> * https://www.qtcentre.org/threads/39525-Configuring-Visual-Studio-for-QT-quot-Error-Cannot-open-source-file-QApplication-quot

Makes sense and thank you as I was wondering why that was. I'll take a look at the links you gave. I'll close the issue but please reply if anyone knows :-)
